/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package freelacademy.telas;

/**
 *
 * @author Marcos Tavares
 */
public class TelaEPortifolio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEPortifolio.class.getName());

    /**
     * Creates new form TelaEPortifolio
     */
    public TelaEPortifolio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Portifolio");
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jToggleButton1.setText("HOME");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(30, 80, 150, 27);

        jToggleButton2.setText("PORTIFOLIO");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(30, 120, 150, 27);

        jToggleButton3.setText("PROJETOS");
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(30, 160, 150, 27);

        jToggleButton4.setText("CARTEIRA");
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(30, 200, 150, 27);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 170, 720, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 270, 720, 40);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 360, 720, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 460, 720, 40);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(290, 560, 720, 40);

        jButton1.setText("SALVAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 630, 120, 30);

        jButton2.setText("SAIR");
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 630, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos Tavares\\Documents\\NetBeansProjects\\FreelAcademy\\src\\main\\java\\src\\EmpresaPortifolio.png")); // NOI18N
        jLabel1.setText("SAIR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEPortifolio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
